server:
  #servlet:
    #context-path: /
  #port: 8443
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-password: password
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  application:
    name: FuelApplication
  data:
    mongodb:
      host: mongodb.selva-demo-web.svc
      port: 27017
      username: FuelApplicationUser
      password: Password1
      database: FuelApplication
